require("gawlster.plugins")
require("gawlster.keymaps")
require("gawlster.options")
require("gawlster.colorscheme")
require("gawlster.autocommands")
require("gawlster.lsp")

-- Plugin config files
require("gawlster.telescope")
require("gawlster.oil")
require("gawlster.whichkey")
require("gawlster.bufferline")
require("gawlster.lualine")
require("gawlster.treesitter")
require("gawlster.alpha")
require("gawlster.autopairs")
require("gawlster.cmp")
require("gawlster.comment")
require("gawlster.gitsigns")
require("gawlster.highlightcolors")
